// Generated by https://quicktype.io

export interface DataBook {
  title: string;
  pages: number;
  genre: string;
  cover: string;
  synopsis: string;
  year: number;
  ISBN: string;
  author: Author;
}

export interface Library {
  library: Book[];
}

export interface Book {
  book: DataBook;
}

export interface Author {
  name: string;
  otherBooks: string[];
}
